/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-05 16:09:48 UTC)
 * on 2013-06-19 at 08:33:32 UTC 
 * Modify at your own risk.
 */

package com.tldr.com.tldr.userinfoendpoint.model;

/**
 * Model definition for UserInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> acceptedTasks;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer faction;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> finishedGoals;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double geoLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double geoLon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String username;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getAcceptedTasks() {
    return acceptedTasks;
  }

  /**
   * @param acceptedTasks acceptedTasks or {@code null} for none
   */
  public UserInfo setAcceptedTasks(java.util.List<java.lang.Long> acceptedTasks) {
    this.acceptedTasks = acceptedTasks;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public UserInfo setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFaction() {
    return faction;
  }

  /**
   * @param faction faction or {@code null} for none
   */
  public UserInfo setFaction(java.lang.Integer faction) {
    this.faction = faction;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getFinishedGoals() {
    return finishedGoals;
  }

  /**
   * @param finishedGoals finishedGoals or {@code null} for none
   */
  public UserInfo setFinishedGoals(java.util.List<java.lang.Long> finishedGoals) {
    this.finishedGoals = finishedGoals;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getGeoLat() {
    return geoLat;
  }

  /**
   * @param geoLat geoLat or {@code null} for none
   */
  public UserInfo setGeoLat(java.lang.Double geoLat) {
    this.geoLat = geoLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getGeoLon() {
    return geoLon;
  }

  /**
   * @param geoLon geoLon or {@code null} for none
   */
  public UserInfo setGeoLon(java.lang.Double geoLon) {
    this.geoLon = geoLon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public UserInfo setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUsername() {
    return username;
  }

  /**
   * @param username username or {@code null} for none
   */
  public UserInfo setUsername(java.lang.String username) {
    this.username = username;
    return this;
  }

  @Override
  public UserInfo set(String fieldName, Object value) {
    return (UserInfo) super.set(fieldName, value);
  }

  @Override
  public UserInfo clone() {
    return (UserInfo) super.clone();
  }

}
